apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetris-game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tetris-game
  template:
    metadata:
      labels:
        app: tetris-game
    spec:
      containers:
        - name: tetrisgame
          image: registry.patrick.dev.br/library/tetris-game:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: tetrisgame-svc
spec:
  selector:
    app: tetris-game
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tetrisgame-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: patrick.dev.br
      http:
        paths:
          - path: /tetris-game
            pathType: Prefix
            backend:
              service:
                name: tetrisgame-svc
                port:
                  number: 3000